# DocuChat Web UI Docker Compose Configuration
# This sets up the complete DocuChat environment with Ollama integration

version: '3.8'

services:
  # DocuChat Web UI Service
  docuchat-web:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: docuchat-web-ui
    restart: unless-stopped
    ports:
      - "7860:7860"
    volumes:
      # Persist vector database
      - docuchat-data:/app/chroma
      # Mount document directories (customize as needed)
      - ./documents:/app/documents:ro
      # Persist logs
      - ./logs:/app/logs
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
      - PYTHONUNBUFFERED=1
    depends_on:
      - ollama
    networks:
      - docuchat-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Ollama LLM Service
  ollama:
    image: ollama/ollama:latest
    container_name: docuchat-ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      # Persist models and data
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0:11434
    networks:
      - docuchat-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    # Pull required model on startup
    command: >
      bash -c "ollama serve & 
               sleep 10 && 
               ollama pull gemma3:270m && 
               wait"

  # Nginx Reverse Proxy (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: docuchat-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - docuchat-web
    networks:
      - docuchat-network
    profiles:
      - production

volumes:
  docuchat-data:
    driver: local
  ollama-data:
    driver: local

networks:
  docuchat-network:
    driver: bridge